### ISSUE TITLE
ADMIN - Create login API which will identify the role and store information of a user

### ISSUE THREAD

**Issue by ASHFAQPATWARI** [NoorRegistry/admin-panel-backend#1]
Create a login api which takes username and password and returns an access_token and refresh_token and token should have the information about user role.
If user is super admin, then display a different UI. Super admin can also have different roles. May be we need a better word for super admin. may be something like internal admin or something. 

If user is store admin then display different UI

**Comment by murtazaamet** [comment]
Completes the Admin Module CRUD Backend below is the schema.

Id: in uuid fornat
username
password
email
role: INTERNAL_ADMIN/STORE_ADMIN
store_id
permissions: default empty array in json format
is_active: for admin status
created_at
updated_at
